### ISSUE TITLE
no module named aes

### ISSUE THREAD

**Issue by DarthMDev** [nirai-compiler/src#2]
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mgracer48/Desktop/Toontown-Empire/Toontown Empire/src/build/make.py", line 9, in <module>
    from niraitools import *
  File "nirai/src/niraitools.py", line 9, in <module>
    import aes
ImportError: No module named aes

**Comment by AskAlice** [comment]
thanks for the elaboration :'(
